/**
 * Intent Handler - Clean Routing Based on Intent Classification
 *
 * This module handles the intent-first pipeline:
 * 1. Classify the user's intent
 * 2. Determine appropriate action based on intent + stage
 * 3. Route to appropriate handler or apply enforcement
 *
 * It replaces the fragile regex-based approach with a robust,
 * intent-driven architecture.
 */

import type { TeachingStage } from "@/lib/mentorContext";
import { classifyIntent, type IntentClassification, shouldSkipCacheLookup } from "./intentClassifier";
import { enforceStage, type EnforcementAction, type EnforcementContext } from "./stageController";
import { validateAIResponse, type ValidationResult } from "@/lib/responseValidator";
import { debug } from "@/lib/debug";

// ─────────────────────────────────────────────────────────────────────────────
// HANDLER RESPONSE TYPES
// ─────────────────────────────────────────────────────────────────────────────

export type HandlerResponse = {
  action: EnforcementAction;
  validation: ValidationResult;
  shouldProceed: boolean;
  modifiedResponse?: string;
  metadata: {
    intent: IntentClassification;
    stage: TeachingStage;
    enforcementApplied: boolean;
    validationApplied: boolean;
  };
};

// ─────────────────────────────────────────────────────────────────────────────
// MAIN INTENT HANDLER
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Process user input through the intent-first pipeline.
 *
 * This is the PRIMARY ENTRY POINT for handling user questions.
 * It ensures every request goes through:
 *   1. Intent classification
 *   2. Stage-based enforcement
 *   3. Response validation
 *
 * @param input - The user's question or statement
 * @param currentStage - The student's current teaching stage
 * @param context - Additional context for enforcement decisions
 * @returns A HandlerResponse with all decisions and validations
 */
export async function handleIntent(
  input: string,
  currentStage: TeachingStage,
  context: EnforcementContext = {}
): Promise<HandlerResponse> {
  const timer = debug.timer("intentHandler");

  try {
    // ─── LAYER 1: Intent Classification ───
    debug.mentor("Classifying intent for input", { inputLength: input.length });
    const intent = classifyIntent(input);

    // ─── LAYER 2: Stage-Based Enforcement ───
    debug.mentor("Enforcing stage constraints", { stage: currentStage, intent: intent.intent });
    const enforcementAction = enforceStage(intent, currentStage, context);

    // ─── LAYER 3: Response Generation (simulated here) ───
    // In the real system, this would generate or retrieve the actual response
    // For now, we'll validate that the enforcement action itself would produce
    // an appropriate response
    let validationResult: ValidationResult = {
      isValid: true,
      severity: "none",
      violations: [],
      metadata: {
        codeBlockCount: 0,
        lineCount: 0,
        hasFunctions: false,
        hasFullSolution: false
      }
    };

    let modifiedResponse: string | undefined;
    let shouldProceed = true;

    // Determine if we should proceed or apply redirection
    switch (enforcementAction.type) {
      case "ALLOW":
        // Proceed normally - response will be generated by AI/Cache
        shouldProceed = true;
        break;

      case "REDIRECT":
        // Generate a redirect response
        modifiedResponse = generateRedirectResponse(enforcementAction, intent, currentStage);
        shouldProceed = false;
        break;

      case "BLOCK":
        // Generate a blocked response with fallback guidance
        modifiedResponse = generateBlockedResponse(enforcementAction, intent, currentStage);
        shouldProceed = false;
        break;

      case "ESCALATE":
        // Escalate to human or special handling
        modifiedResponse = generateEscalationResponse(enforcementAction, intent, currentStage);
        shouldProceed = false;
        break;
    }

    // ─── LAYER 4: Output Validation ───
    // Validate any generated response against stage constraints
    const responseToValidate = modifiedResponse || "[response would be generated here]";
    validationResult = validateAIResponse(responseToValidate, currentStage, intent);

    // If validation failed for a generated response, apply fixes
    if (!validationResult.isValid && modifiedResponse) {
      modifiedResponse = validationResult.rewrittenResponse || modifiedResponse;
    }

    timer();

    return {
      action: enforcementAction,
      validation: validationResult,
      shouldProceed,
      modifiedResponse,
      metadata: {
        intent,
        stage: currentStage,
        enforcementApplied: enforcementAction.type !== "ALLOW",
        validationApplied: !validationResult.isValid
      }
    };

  } catch (error) {
    console.error("[IntentHandler] Error processing intent:", error);

    return {
      action: {
        type: "ESCALATE",
        reason: "Error processing intent classification",
        requiredAction: "Fall back to safe default behavior"
      },
      validation: {
        isValid: false,
        severity: "critical",
        violations: [{
          type: "solution_reveal",
          severity: "critical",
          message: "Error in intent processing - failing safe"
        }],
        metadata: {
          codeBlockCount: 0,
          lineCount: 0,
          hasFunctions: false,
          hasFullSolution: false
        }
      },
      shouldProceed: false,
      modifiedResponse: "I'm having trouble understanding. Let's take a step back and try again. " +
                       "Can you tell me in your own words what you're trying to understand?",
      metadata: {
        intent: {
          intent: "hint_request",
          confidence: "low",
          shouldEnforceStage: true,
          requiresValidation: true,
          reason: "Fallback due to error",
          keywords: []
        },
        stage: currentStage,
        enforcementApplied: true,
        validationApplied: true
      }
    };
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// RESPONSE GENERATORS FOR ENFORCEMENT ACTIONS
// ─────────────────────────────────────────────────────────────────────────────

function generateRedirectResponse(
  action: Extract<EnforcementAction, { type: "REDIRECT" }>,
  intent: IntentClassification,
  stage: TeachingStage
): string {
  const stageNames: Record<TeachingStage, string> = {
    "EXPLORE": "problem understanding",
    "STRATEGIZE": "strategy development",
    "IMPLEMENT": "implementation",
    "DEBUG": "debugging",
    "STUCK": "getting unstuck",
    "REFLECT": "reflection"
  };

  let response = `I understand you're asking about this during the ${stageNames[stage]} phase. `;
  response += `${action.guidance}\n\n`;
  response += `**Suggestion:** ${action.suggestion}\n\n`;

  if (intent.intent === "solution_request") {
    response += `Remember: My role is to help you *discover* the solution yourself, ` +
                `not to provide it directly. This approach leads to deeper learning and ` +
                `better problem-solving skills.`;
  }

  return response;
}

function generateBlockedResponse(
  action: Extract<EnforcementAction, { type: "BLOCK" }>,
  intent: IntentClassification,
  stage: TeachingStage
): string {
  let response = action.message + "\n\n";
  response += `${action.fallbackBehavior}\n\n`;

  // Add educational framing
  if (intent.intent === "solution_request") {
    const stageExplanations: Record<TeachingStage, string> = {
      "EXPLORE": "We need to build your understanding of the problem first.",
      "STRATEGIZE": "You need to develop your own approach before seeing a solution.",
      "IMPLEMENT": "You need to practice translating your ideas into code.",
      "DEBUG": "You need to develop your debugging skills to solve future problems.",
      "STUCK": "Working through challenges builds resilience and expertise.",
      "REFLECT": "Let's review what you've learned from your own solution."
    };

    response += `\n*Why I can't provide the solution:* ${stageExplanations[stage]}\n`;
    response += `\n**Alternative approach:** Tell me what you've tried, and I'll help you `;
    response += `identify the next step. If you're truly stuck, describe your current `;
    response += `understanding, and we'll work through it together.`;
  }

  return response;
}

function generateEscalationResponse(
  action: Extract<EnforcementAction, { type: "ESCALATE" }>,
  intent: IntentClassification,
  stage: TeachingStage
): string {
  let response = `I can see you're in a challenging situation. ${action.reason}\n\n`;
  response += `**What we should do:** ${action.requiredAction}\n\n`;

  response += `Let's try this:\n`;
  response += `1. Take a deep breath\n`;
  response += `2. Tell me, in simple terms, what you understand so far\n`;
  response += `3. Point to the specific place where things get confusing\n\n`;

  if (intent.intent === "frustration") {
    response += `**Remember:** Every programmer, even experts, gets stuck. `;
    response += `The fact that you're working through this shows you're learning.\n`;
  }

  response += `\nI'm here to support you through this, not to give up on you.`;

  return response;
}

// ─────────────────────────────────────────────────────────────────────────────
// BATCH PROCESSING (for testing/analytics)
// ─────────────────────────────────────────────────────────────────────────────

export async function processBatchIntents(
  inputs: Array<{ input: string; stage: TeachingStage; context?: EnforcementContext }>
): Promise<Array<HandlerResponse & { input: string }>> {
  const results: Array<HandlerResponse & { input: string }> = [];

  for (const { input, stage, context } of inputs) {
    const result = await handleIntent(input, stage, context);
    results.push({ ...result, input });
  }

  return results;
}

// ─────────────────────────────────────────────────────────────────────────────
// CACHE ELIGIBILITY CHECK
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Determines if a response should be eligible for caching.
 * This combines intent classification with stage enforcement results.
 */
export function shouldCacheResponse(
  intent: IntentClassification,
  enforcementAction: EnforcementAction,
  stage: TeachingStage
): { shouldCache: boolean; reason: string } {
  // Don't cache if enforcement action blocks or redirects
  if (enforcementAction.type !== "ALLOW") {
    return {
      shouldCache: false,
      reason: `Enforcement action (${enforcementAction.type}) indicates non-standard handling`
    };
  }

  // Use intent classification's cacheability rules
  if (!intent.shouldEnforceStage) {
    return {
      shouldCache: false,
      reason: "Intent does not require stage enforcement"
    };
  }

  // Don't cache solution requests ever
  if (intent.intent === "solution_request") {
    return {
      shouldCache: false,
      reason: "Solution requests should never be cached"
    };
  }

  // Check intent-specific cacheability
  const cacheableIntents: IntentType[] = [
    "understanding",
    "hint_request",
    "clarification",
    "pattern_recognition",
    "transfer_learning",
    "optimization",
    "approach_validation",
    "edge_case_help"
  ];

  if (!cacheableIntents.includes(intent.intent)) {
    return {
      shouldCache: false,
      reason: `Intent type "${intent.intent}" is not cacheable`
    };
  }

  // Early stages have stricter caching (only truly generic advice)
  if (stage === "EXPLORE" && intent.intent !== "understanding" && intent.intent !== "clarification") {
    return {
      shouldCache: false,
      reason: "EXPLORE stage responses are too context-specific to cache"
    };
  }

  return {
    shouldCache: true,
    reason: "Response meets all cache eligibility criteria"
  };
}

// Type exports for convenience
export type { IntentType, IntentConfidence, EnforcementContext };
